site_name: 'market.clearing <br><small><i>economic research and opinion.</i></small>'

nav:
  - About: 
    - about/index.md
    - "Frederik Bennhoff":
      - "CV": "cvs/cv_fhb.md"
      - "Research": "research/index.md"
    - "Igli Bajo"
  - "Blog": "blog/index.md"
  - "Short Courses & Resources":
    - "Solving Economic Models": 
      - 1 Numpy: ./sem/1-numpy.md
      - 2 Numba: ./sem/2-numba.md
      - "3 Application: Stochastic Processes": ./sem/3-application_stoch_proc.md
      - 4 Optimization: ./sem/4-optimization.md
      - 5 Endogenous Grid Method: ./sem/5-endogenous_grid_method.md

theme:
  custom_dir: material
  name: "material"
  features:
    - navigation.top
  #favicon: "static/favicon.ico"
  logo: "static/logo_bold_small.jpg"  # Update the path to your logo
  # logo:
  #   icon: "home"
  #palette:
  #  primary: "white" #"blue grey"
  #  accent: "teal"
  font:
    text: "IBM Plex Serif"
    code: "IBM Plex Mono"
  extra:
    social:
      - type: "github"
        link: "https://github.com/FredHB"
      - type: "linkedin"
        link: "https://linkedin.com/in/fbennhoff"

markdown_extensions:
  - pymdownx.arithmatex  # Render LaTeX math
  - pymdownx.superfences  # Enhanced fenced code blocks
  - pymdownx.highlight  # Syntax highlighting
  - pymdownx.inlinehilite  # Inline syntax highlighting
  - pymdownx.betterem:  # Improved emphasis
      smart_enable: all
  - pymdownx.caret  # Insertions and deletions
  - pymdownx.critic  # Critic markup
  - pymdownx.details  # Details and summary tags
  - pymdownx.emoji:  # Emoji support
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink  # Auto-linking URLs
  - pymdownx.mark  # Highlight text
  - pymdownx.smartsymbols  # Convert ASCII symbols to Unicode
  - pymdownx.tasklist:  # Task lists with checkboxes
      custom_checkbox: true
  - pymdownx.tilde  # Strikethrough text
  - toc:  # Table of contents
      permalink: "#"
  - smarty  # Smart quotes and dashes
  - admonition  # Admonition blocks
  - footnotes  # Footnotes support
  - codehilite  # Code highlighting
#  - fontawesome_markdown  # FontAwesome icons
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details

extra_css:
  - "stylesheets/extra.css"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML